# Plain MQTT protocol
listener 1883
protocol mqtt

# TLS MQTT protocol
listener 8883
protocol mqtt

# Plain WebSockets configuration
# listener 8001
# protocol websockets

auth_plugin /mosquitto/go-auth.so
auth_opt_log_level debug

auth_opt_backends http
auth_opt_check_prefix false
allow_anonymous false

# HTTP backend configuration
auth_opt_http_host app
auth_opt_http_port 8000
auth_opt_http_response_mode json
auth_opt_disable_superuser true

auth_opt_http_getuser_uri /api/v1/mqtt/auth
auth_opt_http_aclcheck_uri /api/v1/mqtt/acl
auth_opt_http_timeout 5