services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy
  
  mosquitto:
    image: iegomez/mosquitto-go-auth:2.1.0-mosquitto_1.6.14
    container_name: mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/certs:/mosquitto/certs:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 8883:8883
    depends_on:
      - app

volumes:
  pgdata: