"""update devices and measurements tables

Revision ID: 138895d43617
Revises: 33e136eb7a9a
Create Date: 2026-08-07 16:20:04.723850

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '138895d43617'
down_revision: str | Sequence[str] | None = '33e136eb7a9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'devices', ['username'])
    op.drop_column('devices', 'name')
    op.add_column('measurements', sa.Column('co2', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('illuminance', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('sound', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('occupancy', sa.Integer(), nullable=True))
    op.drop_column('measurements', 'value')
    op.drop_column('measurements', 'metric_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('metric_type', postgresql.ENUM('CO2', 'TEMPERATURE', 'HUMIDITY', 'ILLUMINANCE', 'SOUND', 'OCCUPANCY', name='metricenum'), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('measurements', 'occupancy')
    op.drop_column('measurements', 'sound')
    op.drop_column('measurements', 'illuminance')
    op.drop_column('measurements', 'humidity')
    op.drop_column('measurements', 'temperature')
    op.drop_column('measurements', 'co2')
    op.add_column('devices', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'hashed_password')
    op.drop_column('devices', 'username')
    # ### end Alembic commands ###
