"""unique classroom name

Revision ID: 33e136eb7a9a
Revises: 8e8eddf93f70
Create Date: 2026-07-30 09:29:01.405706

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e136eb7a9a'
down_revision: str | Sequence[str] | None = '8e8eddf93f70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_classrooms_name', 'classrooms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_classrooms_name', 'classrooms', type_='unique')
    # ### end Alembic commands ###
