"""init schema

Revision ID: 8e8eddf93f70
Revises: 
Create Date: 2026-07-28 21:59:41.527470

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8eddf93f70'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.Enum('USER', 'CLASSROOM', 'DEVICE', 'DEVICE_CONFIG', 'SENSOR_CONFIG', 'SCHEDULE', name='auditentitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='devicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('CO2', 'TEMPERATURE', 'HUMIDITY', 'ILLUMINANCE', 'SOUND', 'OCCUPANCY', name='metricenum'), nullable=False),
    sa.Column('direction', sa.Enum('ABOVE', 'BELOW', name='anomalydirection'), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('triggering_value', sa.Float(), nullable=False),
    sa.Column('peak_value', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_device_started', 'anomaly_logs', ['device_id', 'started_at'], unique=False)
    op.create_index('uq_anomaly_open', 'anomaly_logs', ['device_id', 'metric_type'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('device_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('measurement_interval', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('on_schedule', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('CO2', 'TEMPERATURE', 'HUMIDITY', 'ILLUMINANCE', 'SOUND', 'OCCUPANCY', name='metricenum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_config_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['device_config_id'], ['device_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_config_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('CO2', 'TEMPERATURE', 'HUMIDITY', 'ILLUMINANCE', 'SOUND', 'OCCUPANCY', name='metricenum'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_config_id'], ['device_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_config_id', 'metric_type', name='uq_device_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_configs')
    op.drop_table('schedules')
    op.drop_table('measurements')
    op.drop_table('device_configs')
    op.drop_index('uq_anomaly_open', table_name='anomaly_logs', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index('ix_anomaly_device_started', table_name='anomaly_logs')
    op.drop_table('anomaly_logs')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('classrooms')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for enum_name in (
        'anomalydirection',
        'auditaction',
        'auditentitytype',
        'devicestatus',
        'metricenum',
        'role',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
